### ISSUE TITLE
Most of the models are missing

### ISSUE THREAD

**Issue by nooralahzadeh** [Stanford-AIMI/chexpert-plus#1]
Hi, 

Thanks for sharing this impressive work and dataset.
Several models that are supposed to be part of the project are missing from the repository such as XrayCLIP, XrayVQ-GAN. 
It would be great if you could provide these checkpoints.

Thanks,

**Comment by jbdel** [comment]
Hello,

The models were private, I just changed it to public.
Best,
JB
